{% set name = "app-model" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3b2a0731c053a5e19a1447e222ff46212467cb3db0890ff7794ccf9079d33d31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - psygnal >=0.3.4
    - pydantic >=1.8
    - pydantic-compat >=0.1.1
    - in-n-out >=0.1.5
    - typing_extensions

test:
  imports:
    - app_model
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pyapp-kit/app-model
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Generic application schema implemented in python.
  doc_url: https://app-model.readthedocs.io
  dev_url: https://github.com/pyapp-kit/app-model

extra:
  recipe-maintainers:
    - tlambert03
