{% set name = "app-model" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ccf667999f6c659e921ca3490b6da176971e67cf2f41abc34e33caa8cfa18573

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - psygnal >=0.3.4
    - pydantic >=1.8
    - pydantic-compat >=0.1.1
    - in-n-out >=0.1.5
    - typing_extensions

test:
  imports:
    - app_model
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pyapp-kit/app-model
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Generic application schema implemented in python.
  doc_url: https://app-model.readthedocs.io
  dev_url: https://github.com/pyapp-kit/app-model

extra:
  recipe-maintainers:
    - tlambert03
