{% set name = "app-model" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95136791ad295ccd9c00f42bce34e3655b15099932ee92bf136bd33ca4d548ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - psygnal
    - pydantic
    - in-n-out >=0.1.3
    - typing_extensions

test:
  imports:
    - app_model
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/napari/app-model
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Generic application schema implemented in python.
  doc_url: https://app-model.readthedocs.io
  dev_url: https://github.com/napari/app-model

extra:
  recipe-maintainers:
    - tlambert03
